project_id = "jfdicaamcralxtmvqcag"

[functions.create-pix-payment]
verify_jwt = false

[functions.vizzionpay-webhook]
verify_jwt = false

[functions.check-payment-status]
verify_jwt = false

[functions.verify-turnstile]
verify_jwt = false

[functions.create-reseller-pix]
verify_jwt = false

[functions.reseller-webhook]
verify_jwt = false

[functions.check-reseller-status]
verify_jwt = false
